// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFile(arg1, arg2) {
  return window['go']['main']['App']['AcceptFile'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsSSEConnected() {
  return window['go']['main']['App']['IsSSEConnected']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SendFiles(arg1) {
  return window['go']['main']['App']['SendFiles'](arg1);
}

export function StartClientMode(arg1) {
  return window['go']['main']['App']['StartClientMode'](arg1);
}

export function StartServerMode(arg1) {
  return window['go']['main']['App']['StartServerMode'](arg1);
}

export function StartSync() {
  return window['go']['main']['App']['StartSync']();
}

export function StopSync() {
  return window['go']['main']['App']['StopSync']();
}
