// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ConnectToServer(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetConfig():Promise<config.Config>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartServer(arg1:number):Promise<void>;

export function StopServer():Promise<void>;
