// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {shared} from '../models';

export function GetConfig():Promise<shared.ConfigRequest>;

export function GetStatus():Promise<shared.StatusResponse>;

export function IsSSEConnected():Promise<boolean>;

export function SaveConfig(arg1:shared.ConfigRequest):Promise<void>;

export function StartClientMode(arg1:string):Promise<void>;

export function StartServerMode(arg1:number):Promise<void>;

export function StartSync():Promise<void>;

export function StopSync():Promise<void>;
